### ISSUE TITLE
Single-Letter Abbreviations for Days

### ISSUE THREAD

**Issue by emm-an-uel** [hugomfandrade/CalendarView-Widget#11]
Hey hugo, I like what you've provided with this calendar view widget but I was just hoping there was a way I could replace the names of the days of the week (on top of the calendar view) with single-letter abbreviations instead? ie Monday would be M, Tuesday would be T etc. Is there a way I could do this? Cheers

**Comment by hugomfandrade** [comment]
Hi, unfortunately I did not provide this as an option in the form of an attribute. However, if you could alter the code, I would suggest you look at line 336 of the CalendarView.java file, where you can find the line 
"weekHeaderTexts[i] = simpleText(new DateFormatSymbols().getWeekdays()[dayIndex]);"

calling the 'substring' method could be enough
"weekHeaderTexts[i] = simpleText(new DateFormatSymbols().getWeekdays()[dayIndex])**.substring(0, 1)**;"

**Comment by emm-an-uel** [comment]
cheers, I'll try that out
