### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by franquicidad** [hugomfandrade/CalendarView-Widget#3]
Hello Hugo do you by chance have a part where it send notifications to the user in the time the event is created? or can please give me an idea of how to acomplish this?

**Comment by hugomfandrade** [comment]
Hello
I designed this project with the intent of being used only as a widget/view. Therefore that logic is excluded from the lib but I would recommend you to take a look at JobScheduler

**Comment by franquicidad** [comment]
thank you hugo
