### ISSUE TITLE
No license provided - can I use your Widget in my App?

### ISSUE THREAD

**Issue by tyssiwac** [hugomfandrade/CalendarView-Widget#4]
Hi Hugo,

Unfortunately you didn´t provide any license for your (great) CalendarView Widget. So, legally I´m not allowed to use it in my app but I would like to use it. 
Could you provide a license or contact me via email so that we can agree on the usage of your widget?

Thanks, Sebastian

**Comment by hugomfandrade** [comment]
Hi Sebastian,
I have just released a version with a MIT license. Thanks for pointing it out.

**Comment by tyssiwac** [comment]
Thank you so much!
