### ISSUE TITLE
I want to add text of Event, but how can i...? 

### ISSUE THREAD

**Issue by Comprehensible7** [hugomfandrade/CalendarView-Widget#5]
Hi. @hugomfandrade 

Thank you for providing this great calendar.

I have a question.

If I register a schedule in a calendar,
I want to make it visible, but if I press + to register a schedule, 
the calendar screen will not show the contents of the registration.
I'm not sure which part I should register and modify.

I need your help on this.

Thank you.

included example screenshot @iamAliRaza

and here is my question!
![Screenshot_20200109-002053_Aaaaan_2](https://user-images.githubusercontent.com/57204545/71990422-aee51580-3276-11ea-99b7-eacb89401663.jpg)

<img width="793" alt="Screenshot 2020-01-07 at 7 47 06 PM" src="https://user-images.githubusercontent.com/57204545/71989748-8d375e80-3275-11ea-8f36-0404e5bac756.png">

**Comment by hugomfandrade** [comment]
I did not fully understand your question. From what I understood, the + button is just an activity that creates a pojo which is then added to the calendarview. It does not show its contents

**Comment by Comprehensible7** [comment]
> I did not fully understand your question. From what I understood, the + button is just an activity that creates a pojo which is then added to the calendarview. It does not show its contents

Yes right

I`d like to know how can I show the added contents on this Calendar

Using paint? or canvas? or something else?

and how can I connect the result source?
ex) Java 1 result id-> result id -> show on this calendarview
ex) 1+1 =2 (java 1 result id) -> 2 -> move and showing on this calendarview

Thanks

**Comment by hugomfandrade** [comment]
I haven't implemented this feature yet. When I do, the most straightforward solution is to draw text on the canvas of the onDraw method of the MultipleTriangleView class

**Comment by Comprehensible7** [comment]
> I haven't implemented this feature yet. When I do, the most straightforward solution is to draw text on the canvas of the onDraw method of the MultipleTriangleView class

Thanks for your help

I`ll try your solution

Thanks

**Comment by Comprehensible7** [comment]
> I haven't implemented this feature yet. When I do, the most straightforward solution is to draw text on the canvas of the onDraw method of the MultipleTriangleView class

Hi!

I have one more question!

How can I save the data on this Calendar?

Using SharedPreferences? or something else?

I have no idea how can I do that...

**Comment by hugomfandrade** [comment]
SQLite
